name: 'AI PR Description Assistant'
description: 'Uses AI to generate PR descriptions'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash
    
    - name: Run the action
      run: python src/main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
        PR_TEMPLATE_PATH: ${{ env.PR_TEMPLATE_PATH }}